#!/bin/bash

echo "========================================="
echo "🏭 Swedish Manufacturing Dashboard"
echo "========================================="
echo ""
echo "Quick Start:"
echo "1. Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "2. Run dashboard:"
echo "   python dashboard_simple_server.py"
echo ""
echo "3. Open browser:"
echo "   http://localhost:5000"
echo ""
echo "Full Kafka Mode:"
echo "   See INSTRUCTIONS.txt for details"
echo "========================================="
