#!/bin/bash

echo "=================================================="
echo "🏭 SWEDISH MANUFACTURING DASHBOARD"
echo "=================================================="
echo ""
echo "1. Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "2. Start Kafka (if installed):"
echo "   Terminal 1: zookeeper-server-start config/zookeeper.properties"
echo "   Terminal 2: kafka-server-start config/server.properties"
echo ""
echo "3. Create Kafka topics:"
echo "   kafka-topics --create --topic manufacturing-sensor-data --bootstrap-server localhost:9092"
echo "   kafka-topics --create --topic manufacturing-alerts --bootstrap-server localhost:9092"
echo "   kafka-topics --create --topic manufacturing-system-status --bootstrap-server localhost:9092"
echo "   kafka-topics --create --topic manufacturing-agent-events --bootstrap-server localhost:9092"
echo ""
echo "4. Start Swedish producer (Terminal 3):"
echo "   python kafka_producer_enhanced.py --interval 3"
echo ""
echo "5. Start Swedish dashboard (Terminal 4):"
echo "   python dashboard_app_enhanced.py"
echo ""
echo "6. Open browser: http://localhost:5000"
echo ""
echo "=================================================="
